name: 'Create MacOS package'
inputs:
  otp: # 24.2.1-1, 23.3.4.9-3
    required: true
    type: string
  apple_id_password:
    required: true
    type: string
  apple_developer_identity:
    required: true
    type: string
  apple_developer_id_bundle:
    required: true
    type: string
  apple_developer_id_bundle_password:
    required: true
    type: string
  os:
    required: false
    type: string
    default: macos-11

runs:
  using: composite
  steps:
    - id: prepare
      shell: bash
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_UPGRADE: 1
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        brew update
        brew install curl zip unzip gnu-sed coreutils autoconf automake cmake unixodbc freetds openssl@1.1
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/bin" >> $GITHUB_PATH
        OTP_SOURCE_PATH="$HOME/src/otp-${{ inputs.otp }}"
        OTP_INSTALL_PATH="$HOME/otp/${{ inputs.otp }}"
        echo "OTP_SOURCE_PATH=$OTP_SOURCE_PATH" >> $GITHUB_OUTPUT
        echo "OTP_INSTALL_PATH=$OTP_INSTALL_PATH" >> $GITHUB_OUTPUT
        mkdir -p "$OTP_INSTALL_PATH"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ steps.prepare.outputs.OTP_INSTALL_PATH }}
        key: otp-install-${{ inputs.otp }}-${{ inputs.os }}-static-ssl-disable-hipe-disable-jit
    - name: build erlang
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        OTP_SOURCE_PATH="${{ steps.prepare.outputs.OTP_SOURCE_PATH }}"
        OTP_INSTALL_PATH="${{ steps.prepare.outputs.OTP_INSTALL_PATH }}"
        if [ -d "$OTP_SOURCE_PATH" ]; then
          rm -rf "$OTP_SOURCE_PATH"
        fi
        git clone --depth 1 --branch OTP-${{ inputs.otp }} https://github.com/emqx/otp.git "$OTP_SOURCE_PATH"
        cd "$OTP_SOURCE_PATH"
        ./configure --disable-dynamic-ssl-lib --with-ssl=$(brew --prefix openssl@1.1) --disable-hipe --disable-jit --prefix="$OTP_INSTALL_PATH"
        make -j$(nproc)
        rm -rf "$OTP_INSTALL_PATH"
        make install
    - name: build
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_UPGRADE: 1
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        AUTO_INSTALL_BUILD_DEPS: 1
        APPLE_SIGN_BINARIES: 1
        APPLE_ID: developers@emqx.io
        APPLE_TEAM_ID: 26N6HYJLZA
        APPLE_ID_PASSWORD: ${{ inputs.apple_id_password }}
        APPLE_DEVELOPER_IDENTITY: ${{ inputs.apple_developer_identity }}
        APPLE_DEVELOPER_ID_BUNDLE: ${{ inputs.apple_developer_id_bundle }}
        APPLE_DEVELOPER_ID_BUNDLE_PASSWORD: ${{ inputs.apple_developer_id_bundle_password }}
      shell: bash
      run: |
        export PATH="${{ steps.prepare.outputs.OTP_INSTALL_PATH }}/bin:$PATH"
        make ensure-rebar3
        mkdir -p $HOME/bin
        cp rebar3 $HOME/bin/rebar3
        export PATH="$HOME/bin:$PATH"
        make ${EMQX_NAME}-zip
    - name: test
      shell: bash
      run: |
        export PATH="${{ steps.prepare.outputs.OTP_INSTALL_PATH }}/bin:$PATH"
        pkg_name=$(basename _packages/${EMQX_NAME}/${EMQX_NAME}-*.zip)
        unzip -q _packages/${EMQX_NAME}/$pkg_name
        # test with a spaces in path
        mv ./emqx "./emqx  home/"
        cd "./emqx  home/"
        gsed -i '/emqx_telemetry/d' data/loaded_plugins
        ./bin/emqx start || cat log/erlang.log.1
        ready='no'
        for i in {1..10}; do
          if curl -fs 127.0.0.1:18083 > /dev/null; then
            ready='yes'
            break
          fi
          sleep 1
        done
        if [ "$ready" != "yes" ]; then
          echo "Timed out waiting for emqx to be ready"
          cat log/erlang.log.1
          exit 1
        fi
        ./bin/emqx_ctl status
        if ! ./bin/emqx stop; then
          cat log/erlang.log.1 || true
          cat log/emqx.log.1 || true
          echo "failed to stop emqx"
          exit 1
        fi
        cd ..
        # test with a spaces in path
        rm -rf "emqx  home"
