name: 'Pull request sanity checks'

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

runs:
  using: composite
  steps:
    - name: Run gitlint
      shell: bash
      env:
        BEFORE_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
        AFTER_REF: ${{ github.sha }}
      run: |
        pip install gitlint
        gitlint --commits $BEFORE_REF..$AFTER_REF --config .github/workflows/.gitlint
    - name: Run shellcheck
      shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get update -qy && apt-get install -qy shellcheck
        ./scripts/shellcheck.sh
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
    - name: Check workflow files
      shell: bash
      env:
        ACTIONLINT_VSN: 1.6.25
      run: |
        wget https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VSN}/actionlint_${ACTIONLINT_VSN}_linux_amd64.tar.gz
        tar xfz actionlint_${ACTIONLINT_VSN}_linux_amd64.tar.gz
        # TODO: enable shellcheck when all the current issues are fixed
        ./actionlint -color \
          -shellcheck= \
          -ignore 'label ".+" is unknown' \
          -ignore 'value "emqx-enterprise" in "exclude"'
    - name: Check line-break at EOF
      shell: bash
      run: |
        ./scripts/check-nl-at-eof.sh
    - name: Check apps version
      shell: bash
      run: |
        ./scripts/apps-version-check.sh
    - name: Check Erlang code formatting
      shell: bash
      run: |
        ./scripts/check-format.sh
    - name: Run elvis check
      shell: bash
      run: |
        ./scripts/elvis-check.sh $GITHUB_BASE_REF
    - name: Setup mix
      env:
        MIX_ENV: emqx-enterprise
        PROFILE: emqx-enterprise
      shell: bash
      run: |
        mix local.hex --force && mix local.rebar --force
    - name: Check Elixir code formatting
      env:
        MIX_ENV: emqx-enterprise
        PROFILE: emqx-enterprise
      shell: bash
      run: |
        mix format --check-formatted
