---

name: Elixir Dependency Version Check

on:
  pull_request:

jobs:
  elixir_deps_check:
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/5.0-29:1.13.4-25.1.2-2-ubuntu22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ensure rebar
        run: ./scripts/ensure-rebar3.sh
      - name: Work around https://github.com/actions/checkout/issues/766
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: setup mix
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - name: check elixir deps
        run: ./scripts/check-elixir-deps-discrepancies.exs

...
